version: "3"
services:

  portfolio:
      image: garugaru/portfolio 
      networks:
        - proxy
      deploy:
        labels:
          - traefik.docker.network=proxy
          - traefik.port=80
          - traefik.frontend.rule=Host:garu.io
        mode: replicated
        replicas: 1
        restart_policy:
          condition: on-failure

networks:
  proxy:
    external: true
  internal:
    external: false