version: "3"
services:

  portfolio:
      image: garugaru/portfolio 
      ports:
        - 80:80
      deploy:
        labels:
          - traefik.docker.network=proxy
          - traefik.port=80
          - traefik.frontend.rule=Host:garu.pizza
        mode: replicated
        replicas: 2
        restart_policy:
          condition: on-failure

networks:
  proxy:
    external: true
  internal:
    external: false