version: "3"
services:

  portfolio:
      image: garugaru/portfolio 
      ports:
        - 80:80
      volumes:
        - /swarm/file_store_r2/certs/garu.pizza:/etc/ssl/certs
      deploy:
        replicas: 2
        update_config:
          parallelism: 1
          delay: 5s
        restart_policy:
          condition: on-failure