version: "3"
services:

  portfolio:
      image: garugaru/portfolio 
      ports:
        - 80:80
      deploy:
        replicas: 2
        update_config:
          parallelism: 1
          delay: 10s
        restart_policy:
          condition: on-failure