apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: garu-portfolio-autoscaler
  namespace: personal
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: garu-portfolio
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
